### ISSUE TITLE
[1.20.1] Crash on startup

### ISSUE THREAD

**Issue by Zano1999** [Andrew6rant/Auto-Slabs#23]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'autoslabs'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoSuchFieldError: BETWEEN_MODS_AND_USER
	at io.github.andrew6rant.autoslabs.AutoSlabs.onInitialize(AutoSlabs.java:30)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 14 more

**Comment by Andrew6rant** [comment]
can you post your full logs?

This error looks to be that the method for my ARRP entrypoint can't be found (`NoSuchFieldError: BETWEEN_MODS_AND_USER`), but that shouldn't be possible because I include a compatible ARRP version in AutoSlabs. Are you using a fork, like BRRP?

**Comment by Zano1999** [comment]
I was using both ARRP and BRRP, removing ARRP it starts, below i post the log with both ARRP and BRRP enabled

Latest log: https://pastebin.com/Z0SQ4HXg

**Comment by TriibuNupsik** [comment]
Seems like you got it working @Zano1999, so this can be closed. @Andrew6rant
